### ISSUE TITLE
Objects are not formatted in logpoints

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/vscode-firefox-debug#121]
![image](https://user-images.githubusercontent.com/8599/64667170-ca95f780-d40d-11e9-81ee-5fe96ef52bb3.png)

`bug` should be formatted for inspection, not just toString-ified.

**Comment by hbenl** [comment]
Hmm, in the adapter I just surround the message with ` `` ` and replace `{...}` with `${...}` and send the result to Firefox - to me this is the translation that I would expect.
In any case, what formatting function would you recommend? `JSON.stringify()` doesn't work with all objects, node's `util.inspect()` isn't available because the log expression is evaluated in Firefox...

**Comment by hbenl** [comment]
Aha, so in this case the firefox adapter acts as if we had injected
```
console.log(`Hello ${bug}`)
```
whereas the chrome adapter acts as if we had injected
```
console.log('Hello', bug)
```
That can be very useful, so I'll implement the behavior of the chrome adapter.
