### ISSUE TITLE
Set default settings for temp profiles to reduce noise

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/vscode-firefox-debug#122]
> When using a temporary profile for testing, I want to avoid a fresh onboarding experience/warnings every time, so that I can to focus on debugging.

Follow up from #119.

WebDriver sets these settings https://searchfox.org/mozilla-central/source/testing/geckodriver/src/prefs.rs#16-158 , which we might want to cherry-pick from.

**Comment by hbenl** [comment]
Unfortunately, the only preference for telemetry (at the end of the file) only sets the server, but doesn't disable the telemetry prompt (which is what I think #119 was about). I experimented with a lot of settings in the past but couldn't find anything that disables that prompt - my guess was that this is somehow intentional(?)
By the way, these are the default preferences in this adapter, I guess the list may need some updates:
https://github.com/firefox-devtools/vscode-firefox-debug/blob/34ffc450e4c1ce974201ca2917ebd2534cbc8d30/src/adapter/configuration.ts#L302-L309

**Comment by hbenl** [comment]
Wait, it *is* in there: `"datareporting.policy.dataSubmissionPolicyBypassNotification": true` disables the prompt!

**Comment by digitarald** [comment]
Weird, maybe #119 used an older profile? Webdriver does set `dataSubmissionPolicyBypassNotification` to `true`; maybe that makes the difference?

Looking at the list, here some thoughts on what we might want to carry over:

- `browser.startup.homepage_override.mstone: ignore`: Seems useful for not seeing the new update version – especially when users don't open Firefox often.
- `browser.uitour.enabled: false`: Another UI that might pop up, good to disable.
- `browser.warnOnQuit: false`: Also potentially useful for quick iteration.

**Comment by hbenl** [comment]
What I meant was that the solution for suppressing the telemetry prompt is in the Webdriver settings. I'll still have to add the setting to this adapter.
And thanks for the list of preferences to carry over.

**Comment by digitarald** [comment]
> What I meant was that the solution for suppressing the telemetry prompt is in the Webdriver settings. I'll still have to add the setting to this adapter.

Ha, right; didn't see the `true` reference, I thought you noticed that it is in `configuration.ts`.
