### ISSUE TITLE
pathMappings not working with WSL and Webpack

### ISSUE THREAD

**Issue by Eduardogbg** [firefox-devtools/vscode-firefox-debug#164]
Title. I can't exactly nail down the cause of the bug, but it probably is WSL. I'm using the default create-react-app, so that's how webpack is set.

Maybe I'm messing up with a configuration, idk. I would be very thankful if you guys could help me out with this one. Thanks for the attention.

I'll leave my launch.json and log.

launch.json
`{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "firefox",
      "request": "launch",
      "reAttach": true,
      "name": "Launch Firefox localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}",
      "pathMappings": [
        { "url": "webpack:///*", "path": "/anything/really/*" }
      ],
      "log": {
        "fileName": "C:\\Users\\USUARIO\\Desktop\\log.txt",
        "fileLevel": {
          "default": "Debug"
        }
      }
    }
  ]
}`

[log.txt](https://github.com/firefox-devtools/vscode-firefox-debug/files/3903287/log.txt)

**Comment by hbenl** [comment]
First of all you need to set `webRoot` to `${workspaceFolder}/public` because that is the folder that is served on `http://localhost:3000` by CRA. That should fix the path mapping for `public/veesh.js`.
The second issue is that the CRA sourcemaps are [somewhat broken](https://github.com/facebook/create-react-app/issues/6828), this adapter contains a workaround for this CRA bug, but the workaround doesn't work yet with remote workspaces. I'll try to fix this soon. In the meantime you should be able to fix it with the following pathMapping:
```
{ "url": "http://localhost:3000/home", "path": "vscode-remote://wsl%2Bubuntu/home" }
```
Also, you can remove the path mapping that you already have, it isn't doing anything (`pathMappings` don't contain `*`, unlike the `sourceMapPathOverrides` for the Chrome adapter).

**Comment by Eduardogbg** [comment]
Thanks for your reply and your help, things are working fine now.

**Comment by hbenl** [comment]
FYI: with the new Path Mapping Wizard (added in version 2.6.0), the extension can (usually) figure out the pathMappings automatically.

**Comment by tomcanham** [comment]
So unfortunately I have to give up on remote debugging in WSL(2)/Debian/React (CRA)/Firefox for the time being because I cannot make this work. My last error before deciding "this is too much work, I'll just go back to struggling with the in-browser dev tools" was this:

Unable to open 'immerClass.ts': Unable to read file 'vscode-remote://wsl+debian/home/tom/src/personal/node_chat/src/core/immerClass.ts' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+debian/home/tom/src/personal/node_chat/src/core/immerClass.ts').

I appreciate the work that's gone into this, I just don't see this combo of tools/plugins/system settings as "ready for prime time" development just yet. I know that doing dev on Windows alone is an outlier, as is using Firefox rather than Chrome, as is using Debian under WSL2 rather than Ubuntu, so that with so many outliers together the statistical probability of there being an "easy, obvious solution is... minimal. I'm really not faulting the devs! It's obvious they put in a lot of work, and it's close. But at the end of the day, I'm a working dev, and can't spend more time fighting with my tools than I do writing code -- so I could never use this solution in writing production code (this is a toy project, a POC where I learn how to combine a React/WS based chat client with a golang chat server, but still, the "working dev" part is true. I guess I'll write my production code on a Macbook like the rest of the "sheeple" (lol))

End of rant (not really a rant: I wanted this to work so bad. Debugging real code using webpacked source in the browser dev tools is... painful, to say the least. Especially when the code is highly asynchronous and there are a lot of plates in the air!). But to quote Tupac: "hey. I gotta get paid!"
