### ISSUE TITLE
Firefox snap and Ubuntu 20.04 - Your Firefox profile cannot be loaded.

### ISSUE THREAD

**Issue by duffimc** [firefox-devtools/vscode-firefox-debug#200]
Hi,
I updated ubuntu from 18.04 to 20.04 version and installed the firefox snap.
This is my launch.json:
```
{
  "name": "Launch localhost",
  "type": "firefox",
  "request": "launch",
  "reAttach": true,
  "url": "http://localhost:4200",
  "webRoot": "${workspaceFolder}",
}
```

when I run the debug I get the following popup error:

> Your Firefox profile cannot be loaded. It may be missing or inaccessible.

followed by another message

> connect ECONNREFUSED 127.0.0.1:6000

How can i solve it?
Thanks

**Comment by hbenl** [comment]
The problem seems to be that the snap-packaged version of Firefox is not allowed to access `/tmp`, where this extension usually stores the temporary debug profile. I have added a new configuration property `tmpDir` in version 2.8.0 to change the temporary directory: set it to a directory in your home folder (e.g. `"tmpDir": "/home/duffimc/tmp"`). You may also have to increase the timeout for starting Firefox (e.g. `"timeout": 20`) because the snap-packaged Firefox takes some time to start.

**Comment by mmhasalkar** [comment]
You could also increase the timeout a bit if you still face the `connect ECONNREFUSED 127.0.0.1:6000` error.
