### ISSUE TITLE
Whitelist and/or blacklist the browser tabs to attach

### ISSUE THREAD

**Issue by GuillaumeAmat** [firefox-devtools/vscode-firefox-debug#207]
As @hbenl wrote there: https://github.com/firefox-devtools/vscode-firefox-debug/issues/179#issuecomment-581599879

> [...] the debugger is automatically attached to every browser tab. You should use a separate Firefox window for regular browsing.

That behavior is the uniq reason why I don't use the VSCode debugger. I don't want another Firefox instance to eat up my RAM, despite all the love I have to Firefox :)

Is it possible to consider and discuss about a solution for the one-browser workflow? I can't think I'm the only one in that case, and it's a strong no-go for us.

What about supporting a whitelist and/or a blacklist of the domains/origins we want to attach to, instead of all them (every tabs)?

**Comment by hbenl** [comment]
I have added the `tabFilter` configuration property in version 2.9.0. Examples:
* `"tabFilter": "http://localhost:3000/*"` - only attach to tabs whose URL starts with "http://localhost:3000/"
* `"tabFilter": { "exclude": "*google.com*" }` - attach to any tab except those with google.com URLs

You can also specify string arrays instead of single strings and mix include and exclude patterns: `"tabFilter": { "include": [...], "exclude": [...] }`.

Thanks for the suggestion!

**Comment by GuillaumeAmat** [comment]
Great news thanks! 🎉
