### ISSUE TITLE
Update extension version on open-vsx.org for vscodium

### ISSUE THREAD

**Issue by 0xff8** [firefox-devtools/vscode-firefox-debug#349]
Hi @hbenl ,

The extension on https://open-vsx.org/extension/firefox-devtools/vscode-firefox-debug has no updates for 3+ years and missing very important(at least for me) [bug fix](https://github.com/firefox-devtools/vscode-firefox-debug/pull/329) for MacOS.

Would you be so kind to update it or make someone responsible for updating it? (in case you have no time or interest I could do so) 🥇

**Comment by nchevobbe** [comment]
Hello @0xff8 , we (the Firefox DevTools team), plan to start maintaining this plugin. We're not familiar with the codebase (and have other things to take care of) so the process might take some time.
First we are going to triage existing issues and attempt to review PRs, so we'll look at yours (hopefully soon)

**Comment by Daniel-Khodabakhsh** [comment]
Thanks @nchevobbe 

To add more context. [Open VSX](https://open-vsx.org/) is an extension repository which exists because [Microsoft prohibits usage of the Microsoft marketplace by any editor other than the official VSCode release](https://github.com/microsoft/vscode/issues/31168). This prevented VSCode forks like VSCodium from using the marketplace, so an open market place that can be used by all (including VSCode) was created: Open VSX.

[Here are the publishing steps for Open VSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Currently, the latest version of `firefox-devtools` available on Open VSX is 2.9.1 which is missing the fix which resolves https://github.com/firefox-devtools/vscode-firefox-debug/issues/341 so it's not possible to debug FireFox on any VSCode fork such as VSCodium.

cc: @hbenl : @trysten you requested this 3 months ago, did you have a workaround for people using Open VSX?

**Comment by hbenl** [comment]
Done. I'll keep the extension up-to-date on open-vsx.org in the future.
